spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_database
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    # type: com.zaxxer.hikari.HikariDataSource
    # pool-name: myPool
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true